In [1]:
import numpy as np

### Creating Numpy Arrays from Python Lists

In [2]:
np.array([1,2,3,4])
# Numpy arr will convert all item to the same type
# Ex: np.array([3.14, 4,2,3]) => array([3.14, 4., 2., 3.])

array([1, 2, 3, 4])

### Convert all type of item in numpy array


In [5]:
np.array([1,2,3,4], dtype='float')

array([1., 2., 3., 4.])

### assign numpy array as a variable

In [8]:
a1 = np.array([2,3,4])
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2,3], 
                [2,3,4]])
type(a2)

numpy.ndarray

### view the number of column and row

In [10]:
a2.shape  # 2 row and 3 column

(2, 3)

### kiem tra mang bao nhieu chieu

In [12]:
a2.ndim # a2 la mang 2 chieu

2

### View type of numpy array

In [13]:
a2.dtype

dtype('int32')

### View the number of total element

In [14]:
a2.size

6

# Create numpy array from Scratch

### Zeros

In [17]:
np.zeros((2,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### ones

In [18]:
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### arange

In [21]:
np.arange(0,20, 2) #(start, stop, step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### full

In [22]:
np.full((3,5), 8.2)

array([[8.2, 8.2, 8.2, 8.2, 8.2],
       [8.2, 8.2, 8.2, 8.2, 8.2],
       [8.2, 8.2, 8.2, 8.2, 8.2]])

### linspace

In [26]:
np.linspace(0, 2, 5)  #(start, end, num of item)

array([0. , 0.5, 1. , 1.5, 2. ])

### random


In [28]:
np.random.random((4,4))

array([[0.41986741, 0.63594058, 0.74176705, 0.16538544],
       [0.87257197, 0.28111309, 0.75138605, 0.00376411],
       [0.60740929, 0.9380848 , 0.76872703, 0.76430558],
       [0.15342549, 0.79302336, 0.85864978, 0.329348  ]])

In [36]:
np.random.rand(4,4) # same the code above

array([[0.27417326, 0.79820039, 0.81413841, 0.94809042],
       [0.82288464, 0.51513912, 0.22099815, 0.74663141],
       [0.43153777, 0.88830375, 0.9411933 , 0.50301225],
       [0.70204204, 0.70654201, 0.48102176, 0.96031373]])

In [32]:
# Get the same value after run again
np.random.seed(2)
np.random.random((4,4))

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515]])

In [34]:
np.random.normal(0, 1, (3,3)) # gia tri trung binh bang 0, do lech chuan = 1

array([[-0.23618403, -0.63765501, -1.18761229],
       [-1.42121723, -0.1534952 , -0.26905696],
       [ 2.23136679, -2.43476758,  0.1127265 ]])

In [35]:
np.random.randint(1,10,(2,5)) # (Start, end, shape)

array([[9, 6, 4, 1, 1],
       [3, 9, 9, 3, 7]])

# Array indexing & slicing

### One-dimensional subarray

In [38]:
x1 = np.random.randint(0,20, size=6)
x1

array([17, 15, 13,  7, 11, 15])

In [40]:
x1[4], x1[0], x1[-1]

(11, 17, 15)

### Multi-dimensional array

In [42]:
x2 = np.random.randint(0,10, (3,4))
x2

array([[1, 9, 2, 1],
       [0, 7, 1, 8],
       [9, 0, 7, 0]])

In [44]:
x2[1,1]

7

In [45]:
x2[1,1] = 6
x2

array([[1, 9, 2, 1],
       [0, 6, 1, 8],
       [9, 0, 7, 0]])

### Slicing
x [ start : stop : step ]

In [46]:
x1

array([17, 15, 13,  7, 11, 15])

In [47]:
x1[0:3]

array([17, 15, 13])

In [53]:
x1[::2]

array([17, 13, 11])

In [55]:
x2

array([[1, 9, 2, 1],
       [0, 6, 1, 8],
       [9, 0, 7, 0]])

In [56]:
x2[:2, :3]

array([[1, 9, 2],
       [0, 6, 1]])

In [57]:
x2[:2,:]

array([[1, 9, 2, 1],
       [0, 6, 1, 8]])

# Reshaping of Arrays & Transpose

In [61]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape

In [60]:
grid.reshape((3,3)) # Reshape (9,0) to (3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
x = np.array([1,2,3])

In [63]:
x.shape

(3,)

In [65]:
x.reshape((1,3)).shape

(1, 3)

### Transpose

In [66]:
x = np.array([[2., 1.], [3.,4.]])
x

array([[2., 1.],
       [3., 4.]])

In [68]:
x.T  # Convert row to column 

array([[2., 3.],
       [1., 4.]])

# Array concatenation and splitting

In [70]:
x = np.array([1,2,3])
y = np.array([3,2,1])

### concatenation

In [76]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [79]:
grid = np.array([[1,2,3],
                [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.concatenate((grid, grid)) # default axis = 0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
np.concatenate((grid, grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [87]:
# vstack (Vertical stack)
x = np.array([1,2,3])

grid = np.array([[9,8,7],
                [6,5,4]])
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [88]:
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [90]:
# horizontally stack: hstack 
y = np.array([[99],
              [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### Splitting

In [91]:
x = np.array([1,2,3,99,69,3,2,1])

np.split(x,[3,5])

[array([1, 2, 3]), array([99, 69]), array([3, 2, 1])]

# Broadcasting and Vectorized operations

In [92]:
a = np.arange(3)
a

array([0, 1, 2])

In [93]:
a + 5 # Broadcasting  [0+5,1+5,2+5]

array([5, 6, 7])

In [95]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
a

array([0, 1, 2])

In [97]:
b + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [99]:
c = np.arange(3).reshape(3,1)
c

array([[0],
       [1],
       [2]])

In [100]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Manipulating & Comparing Arrays

### Aggregation


In [102]:
list_number = [1,2,3]

In [104]:
ll = np.array(list_number)
ll

array([1, 2, 3])

In [105]:
sum(ll) # Python sum()   

6

In [106]:
np.sum(ll) # Numpy sum()  (Faster than code above)

6

In [109]:
# Create a massive Numpy array
massive_array = np.random.random(10000)
massive_array.shape

(10000,)

In [111]:
%timeit sum(massive_array)  #Python 
%timeit np.sum(massive_array) #Numpy

603 µs ± 28.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.76 µs ± 215 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [112]:
np.mean(massive_array) #average

0.4966445686366611

In [113]:
np.max(massive_array)

0.9999698510948906

In [115]:
np.min(massive_array)

0.0004605572526041879

# Độ lệch chuẩn và phương sai

In [116]:
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)

### Do lech chuan

In [117]:
np.std(dog_height)

147.32277488562318

### Phuong sai

In [118]:
np.var(dog_height)

21704.0

### Do lech chuan

In [119]:
np.sqrt(np.var(dog_height))

147.32277488562318

# Sorting Array

In [121]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [122]:
np.argsort(x) # return sorted index

array([1, 0, 3, 2, 4], dtype=int64)

### Sorting along rows or column

In [125]:
np.random.seed(42)

MatA = np.random.randint(0,10, (4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [126]:
np.sort(MatA, axis= 0) # Sort by column

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [127]:
np.sort(MatA, axis=1) # Sort by rows

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Linear Algebra

In [129]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
B = np.array([[6,5],
              [4,3],
              [2,1]])
B

array([[6, 5],
       [4, 3],
       [2, 1]])

### Tich vo huong

In [134]:
A.dot(B)   # A(3x3) & B(3x2)
# 1*6 + 2*4 + 3*2 = 20

array([[20, 14],
       [56, 41],
       [92, 68]])

In [135]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

### Dot Product Example

In [136]:
np.random.seed(0)

sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [137]:
# Create weekly_sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index= ["Mon", "Tue", "Wed", "Thurs", "Fri"], 
                            columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [140]:
# Create a price array
prices = np.array([10,8,12])
prices = prices.reshape((1,3))


In [141]:
butter_prices = pd.DataFrame(prices, index=["Price"],
                             columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [142]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [145]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [146]:
total_prices = weekly_sales.dot(butter_prices.T)

In [147]:
total_prices

Price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [148]:
weekly_sales["Total prices"] = total_prices

In [149]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total prices
Mon               12             15              0           240
Tue                3              3              7           138
Wed                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142