In [1]:
import numpy as np


### Create numpy array

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr = np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array(42)
arr

array(42)

In [5]:
arr = np.array([[1,2,3],
               [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### check number of Dimensions

In [6]:
arr.ndim

2

### check numpy version

In [7]:
np.__version__

'1.23.4'

### Get value by index


In [8]:
a = np.array([98,8,2,19,3,6])
a[3]

19

In [9]:
a2 = np.array([[2,5,6],
               [8,9,2],
               [2,88,3]])
a2[1,1]

9

In [10]:
a2[:2,:]

array([[2, 5, 6],
       [8, 9, 2]])

### Get type of item in numpy array

In [11]:
a2.dtype

dtype('int32')

### Change type of numpy array

In [12]:
a2.astype('str')

array([['2', '5', '6'],
       ['8', '9', '2'],
       ['2', '88', '3']], dtype='<U11')

### Copy array



In [13]:
a = np.array([2,3,4,5,8,8])
arr_copy = a.copy()
arr_copy


array([2, 3, 4, 5, 8, 8])

In [14]:
arr_copy.view()

array([2, 3, 4, 5, 8, 8])

### View shape

In [15]:
arr = np.array([[8,4,6],
               [2,7,3],
               [8,9,1],
               [31,7,6]])
arr.shape

(4, 3)

### reshape

In [16]:
arr = np.array([8,9,2,7,3,6,9,87,1,6,8,3])
arr


array([ 8,  9,  2,  7,  3,  6,  9, 87,  1,  6,  8,  3])

In [17]:
arr.reshape((3,4))

array([[ 8,  9,  2,  7],
       [ 3,  6,  9, 87],
       [ 1,  6,  8,  3]])

In [18]:
arr.reshape(2,3,2)

array([[[ 8,  9],
        [ 2,  7],
        [ 3,  6]],

       [[ 9, 87],
        [ 1,  6],
        [ 8,  3]]])

In [19]:
arr = np.array([[[1,65,8],
        [2,7,9],
        [22,6,7]]])
arr.reshape(-1)

array([ 1, 65,  8,  2,  7,  9, 22,  6,  7])

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [21]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


### Joining NumPy Arrays


In [22]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

np.concatenate((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [23]:
a1 = np.array([[1,2,3],
              [4,5,6]])
a2 = np.array([[5,8,9],
               [7,3,6]])

np.concatenate((a1,a2))

array([[1, 2, 3],
       [4, 5, 6],
       [5, 8, 9],
       [7, 3, 6]])

In [24]:
np.concatenate((a1,a2), axis= 1)

array([[1, 2, 3, 5, 8, 9],
       [4, 5, 6, 7, 3, 6]])

In [25]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

np.stack((arr1, arr2), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [27]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

### Splitting array
 

In [28]:
a = np.array([8,9,3,8,7,2])
np.array_split(a, 3)

[array([8, 9]), array([3, 8]), array([7, 2])]

In [32]:
a = np.array([[8,9,7],
              [7,3,9],
              [7,6,9]])
np.array_split(a,3, axis=1)

[array([[8],
        [7],
        [7]]),
 array([[9],
        [3],
        [6]]),
 array([[7],
        [9],
        [9]])]

In [33]:
np.hsplit(a, 3)

[array([[8],
        [7],
        [7]]),
 array([[9],
        [3],
        [6]]),
 array([[7],
        [9],
        [9]])]

In [34]:
np.vsplit(a,3)

[array([[8, 9, 7]]), array([[7, 3, 9]]), array([[7, 6, 9]])]

### Array search

In [47]:
a = np.array([-1,8,7,6,9,2,78,5,7,2,2])
np.where(a == 2) # return the index

(array([ 5,  9, 10], dtype=int64),)

In [48]:
# Search sorted
np.searchsorted(a, 2)

1

In [51]:
a = np.array([1,3,7])
np.searchsorted(a, [2,4,6])  # return the index should be inserted

array([1, 2, 2], dtype=int64)

### Sort

In [54]:
a = np.array([8,7,2,6,7,9])
np.sort(a)

array([2, 6, 7, 7, 8, 9])

In [55]:
a = np.array(['nam', 'an', 'linh'])
np.sort(a)

array(['an', 'linh', 'nam'], dtype='<U4')

In [56]:
a = np.array([[8,7,3,7],
              [7,2,1,6],
              [7,7,2,1]])
np.sort(a)

array([[3, 7, 7, 8],
       [1, 2, 6, 7],
       [1, 2, 7, 7]])

In [58]:
np.sort(a,axis=0)

array([[7, 2, 1, 1],
       [7, 7, 2, 6],
       [8, 7, 3, 7]])

### Filter

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [59]:
a = np.array([8,9,3,4])
x = [True, False, True, False]
a[x]

array([8, 3])

In [60]:
a = np.random.randint(1,11,size=10)
a

array([ 4,  6,  5,  1,  6,  6,  6, 10,  8,  7])

In [61]:
# Filer even number
filter_arr = a % 2 ==0
a[filter_arr]

array([ 4,  6,  6,  6,  6, 10,  8])

### Random


In [62]:
x = np.random.randint(100)
x

67

In [64]:
x = np.random.rand()
x

0.13477627380553747

In [67]:
a = np.random.randint(0,10,(3,6))
a

array([[5, 9, 0, 1, 7, 4],
       [2, 7, 2, 6, 2, 5],
       [6, 6, 3, 7, 9, 7]])

In [69]:
x = np.random.choice([8,9,3,4,7])
x

3

In [71]:
a = np.random.choice([9,3,7,6], (2,3))
a

array([[7, 3, 7],
       [9, 7, 3]])

### Random with frequency

In [73]:
a = np.random.choice([1,2,3,4], p=[0.2,0.7,0.1,0], size=(3,7)) # p la tan suat xuat hien
a

array([[2, 1, 3, 2, 3, 2, 2],
       [2, 2, 2, 2, 2, 1, 2],
       [2, 1, 2, 2, 2, 2, 1]])

### Random permutation

In [78]:
a = np.array([1,2,3,4,5])
np.random.shuffle(a) # Return None
a

array([4, 3, 2, 1, 5])

In [79]:
a2 = np.array([1,2,3,4,5])
np.random.permutation(a) # Return new array

array([2, 5, 4, 1, 3])